"use server";

import { createClient } from "@/lib/supabase/server";
import { stripe } from "@/lib/stripe/server";
import { PLANS, isPlan, type Plan } from "@/lib/plans";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";

// Starts (or replaces) the artist's own paid plan subscription -- the
// artist paying Fyby for a lower commission rate (lib/plans.ts), not to be
// confused with a fan's Super Fan subscription to an artist
// (app/actions/superfan.ts). Same inline price_data checkout pattern as
// that file; the actual plan change happens once Stripe confirms the
// subscription in app/api/webhooks/stripe-subscriptions/route.ts, not here.
export async function startPlanCheckout(formData: FormData) {
  const requestedPlan = formData.get("plan") as string;

    if (!isPlan(requestedPlan) || requestedPlan === "free") {
        throw new Error("Not a valid paid plan.");
          }

            const plan = requestedPlan as Plan;
              const supabase = createClient();

                const {
                    data: { user },
                      } = await supabase.auth.getUser();

                        if (!user) {
                            redirect(
                                  `/login?message=${encodeURIComponent(
                                          "Log in to your artist account to upgrade your plan."
                                                )}&next=${encodeURIComponent("/dashboard")}`
                                                    );
                                                      }

                                                        const { data: artist } = await supabase
                                                            .from("artists")
                                                                .select("id, plan, plan_subscription_id")
                                                                    .eq("user_id", user.id)
                                                                        .maybeSingle();

                                                                          if (!artist) {
                                                                              throw new Error("No artist account found for your login.");
                                                                                }

                                                                                  if ((artist as any).plan === plan) {
                                                                                      throw new Error(`You're already on the ${PLANS[plan].label} plan.`);
                                                                                        }

                                                                                          // Switching straight from one paid plan to another (Artist -> Pro or back)
                                                                                            // without a Stripe Customer Portal in front of it: cancel whatever paid
                                                                                              // subscription is currently running so the artist is never billed for two
                                                                                                // plans at once, then start the new one via checkout below.
                                                                                                  const existingSubscriptionId = (artist as any).plan_subscription_id as string | null;
                                                                                                    if (existingSubscriptionId) {
                                                                                                        try {
                                                                                                              await stripe.subscriptions.cancel(existingSubscriptionId);
                                                                                                                  } catch (err: any) {
                                                                                                                        console.error(`Could not cancel existing plan subscription ${existingSubscriptionId}:`, err.message);
                                                                                                                            }
                                                                                                                              }
                                                                                                                              
                                                                                                                                const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
                                                                                                                                
                                                                                                                                  const session = await stripe.checkout.sessions.create({
                                                                                                                                      mode: "subscription",
                                                                                                                                          billing_address_collection: "required",
                                                                                                                                              line_items: [
                                                                                                                                                    {
                                                                                                                                                            price_data: {
                                                                                                                                                                      currency: "usd",
                                                                                                                                                                                unit_amount: PLANS[plan].priceCents,
                                                                                                                                                                                          recurring: { interval: "month" },
                                                                                                                                                                                                    product_data: {
                                                                                                                                                                                                                name: `Fyby ${PLANS[plan].label} plan`,
                                                                                                                                                                                                                            description: `${(PLANS[plan].rateBps / 100).toFixed(0)}% platform commission instead of Free's ${(PLANS.free.rateBps / 100).toFixed(0)}%.`,
                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                      quantity: 1,
                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                    success_url: `${siteUrl}/dashboard?plan=success`,
                                                                                                                                                                                                                                                                        cancel_url: `${siteUrl}/dashboard`,
                                                                                                                                                                                                                                                                            subscription_data: {
                                                                                                                                                                                                                                                                                  metadata: {
                                                                                                                                                                                                                                                                                          type: "artist_plan_subscription",
                                                                                                                                                                                                                                                                                                  artist_id: artist.id,
                                                                                                                                                                                                                                                                                                          plan,
                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                        metadata: {
                                                                                                                                                                                                                                                                                                                              type: "artist_plan_subscription",
                                                                                                                                                                                                                                                                                                                                    artist_id: artist.id,
                                                                                                                                                                                                                                                                                                                                          plan,
                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                  if (!session.url) {
                                                                                                                                                                                                                                                                                                                                                      throw new Error("Stripe did not return a checkout URL.");
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                          redirect(session.url);
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                          // Cancels at the end of the current paid period rather than immediately, so
                                                                                                                                                                                                                                                                                                                                                          // an artist who cancels keeps the rate they already paid for until it
                                                                                                                                                                                                                                                                                                                                                          // actually runs out -- the downgrade to Free itself happens in the webhook's
                                                                                                                                                                                                                                                                                                                                                          // customer.subscription.deleted branch, which fires when Stripe ends the
                                                                                                                                                                                                                                                                                                                                                          // subscription at that period end, not when this function runs.
                                                                                                                                                                                                                                                                                                                                                          export async function cancelPlanSubscription(): Promise<{ error?: string }> {
                                                                                                                                                                                                                                                                                                                                                            const supabase = createClient();
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                              const {
                                                                                                                                                                                                                                                                                                                                                                  data: { user },
                                                                                                                                                                                                                                                                                                                                                                    } = await supabase.auth.getUser();
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      if (!user) return { error: "Not logged in." };
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                        const { data: artist } = await supabase
                                                                                                                                                                                                                                                                                                                                                                            .from("artists")
                                                                                                                                                                                                                                                                                                                                                                                .select("plan, plan_subscription_id")
                                                                                                                                                                                                                                                                                                                                                                                    .eq("user_id", user.id)
                                                                                                                                                                                                                                                                                                                                                                                        .maybeSingle();
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                          if (!artist) return { error: "No artist account found for your login." };
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                            const subscriptionId = (artist as any).plan_subscription_id as string | null;
                                                                                                                                                                                                                                                                                                                                                                                              if (!subscriptionId || (artist as any).plan === "free") {
                                                                                                                                                                                                                                                                                                                                                                                                  return { error: "You're not on a paid plan." };
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                          await stripe.subscriptions.update(subscriptionId, { cancel_at_period_end: true });
                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                return { error: `Could not cancel: ${err.message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                    revalidatePath("/dashboard");
                                                                                                                                                                                                                                                                                                                                                                                                                      return {};
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                      
