"use server";

import { createClient } from "@/lib/supabase/server";
import { stripe } from "@/lib/stripe/server";
import { redirect } from "next/navigation";

// $9/month Super Fan subscription for one specific artist. Same inline
// price_data pattern as app/actions/checkout.ts's startAlbumCheckout, just
// mode: "subscription" with a recurring interval instead of mode: "payment"
// -- no pre-created Stripe Product/Price needed. The subscription row itself
// (artist_subscriptions) isn't written here; it's written by the dedicated
// webhook at app/api/webhooks/stripe-subscriptions/route.ts once Stripe
// confirms the subscription actually started, same division of labor as
// checkout.ts/the main webhook for one-time purchases.
export async function startSuperFanCheckout(formData: FormData) {
  const artistId = formData.get("artistId") as string;
    const referredByFanId = (formData.get("referredByFanId") as string) || null;

      const supabase = createClient();

        const {
            data: { user },
              } = await supabase.auth.getUser();

                if (!user) {
                    redirect(
                          `/login?message=${encodeURIComponent(
                                  "Log in or sign up to become a Super Fan."
                                        )}&next=${encodeURIComponent(`/artists/${artistId}`)}`
                                            );
                                              }

                                                const { data: artist, error } = await supabase
                                                    .from("artists")
                                                        .select("id, is_active, profiles ( display_name )")
                                                            .eq("id", artistId)
                                                                .single();

                                                                  if (error || !artist) {
                                                                      throw new Error("Could not find that artist.");
                                                                        }

                                                                          if ((artist as any).is_active === false) {
                                                                              throw new Error("This artist isn't available for Super Fan support right now.");
                                                                                }

                                                                                  const { data: existing } = await supabase
                                                                                      .from("artist_subscriptions")
                                                                                          .select("id, status")
                                                                                              .eq("fan_id", user.id)
                                                                                                  .eq("artist_id", artistId)
                                                                                                      .eq("status", "active")
                                                                                                          .maybeSingle();
                                                                                                          
                                                                                                            if (existing) {
                                                                                                                throw new Error("You're already a Super Fan of this artist.");
                                                                                                                  }
                                                                                                                  
                                                                                                                    const artistName = (artist as any).profiles?.display_name ?? "this artist";
                                                                                                                      const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
                                                                                                                      
                                                                                                                        const session = await stripe.checkout.sessions.create({
                                                                                                                            mode: "subscription",
                                                                                                                                billing_address_collection: "required",
                                                                                                                                    line_items: [
                                                                                                                                          {
                                                                                                                                                  price_data: {
                                                                                                                                                            currency: "usd",
                                                                                                                                                                      unit_amount: 900,
                                                                                                                                                                                recurring: { interval: "month" },
                                                                                                                                                                                          product_data: {
                                                                                                                                                                                                      name: `Super Fan -- ${artistName}`,
                                                                                                                                                                                                                  description:
                                                                                                                                                                                                                                "Monthly support with exclusive content, shoutouts, private show videos, and the two-way video exchange.",
                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                          quantity: 1,
                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                        success_url: `${siteUrl}/artists/${artistId}?superfan=success`,
                                                                                                                                                                                                                                                                            cancel_url: `${siteUrl}/artists/${artistId}`,
                                                                                                                                                                                                                                                                                subscription_data: {
                                                                                                                                                                                                                                                                                      metadata: {
                                                                                                                                                                                                                                                                                              type: "superfan_subscription",
                                                                                                                                                                                                                                                                                                      artist_id: artistId,
                                                                                                                                                                                                                                                                                                              fan_id: user.id,
                                                                                                                                                                                                                                                                                                                      ...(referredByFanId ? { referred_by_fan_id: referredByFanId } : {}),
                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                    metadata: {
                                                                                                                                                                                                                                                                                                                                          type: "superfan_subscription",
                                                                                                                                                                                                                                                                                                                                                artist_id: artistId,
                                                                                                                                                                                                                                                                                                                                                      fan_id: user.id,
                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                              if (!session.url) {
                                                                                                                                                                                                                                                                                                                                                                  throw new Error("Stripe did not return a checkout URL.");
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      redirect(session.url);
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                      // A one-time monetary gift straight to the artist, separate from buying a
                                                                                                                                                                                                                                                                                                                                                                      // track/album or subscribing. Same shape as startCheckout in checkout.ts,
                                                                                                                                                                                                                                                                                                                                                                      // but the amount is fan-chosen rather than one of the fixed track/album
                                                                                                                                                                                                                                                                                                                                                                      // price tiers. Recorded by the existing one-time-purchase webhook (app/api/
                                                                                                                                                                                                                                                                                                                                                                      // webhooks/stripe/route.ts) since it's a mode: "payment" session like any
                                                                                                                                                                                                                                                                                                                                                                      // other purchase, not a subscription.
                                                                                                                                                                                                                                                                                                                                                                      export async function startGiftCheckout(formData: FormData) {
                                                                                                                                                                                                                                                                                                                                                                        const artistId = formData.get("artistId") as string;
                                                                                                                                                                                                                                                                                                                                                                          const amountDollars = Number(formData.get("amount"));
                                                                                                                                                                                                                                                                                                                                                                            const message = (formData.get("message") as string) || null;
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                              if (!amountDollars || amountDollars < 1) {
                                                                                                                                                                                                                                                                                                                                                                                  throw new Error("Enter a gift amount of at least $1.");
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                      const supabase = createClient();
                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                        const {
                                                                                                                                                                                                                                                                                                                                                                                            data: { user },
                                                                                                                                                                                                                                                                                                                                                                                              } = await supabase.auth.getUser();
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                if (!user) {
                                                                                                                                                                                                                                                                                                                                                                                                    redirect(
                                                                                                                                                                                                                                                                                                                                                                                                          `/login?message=${encodeURIComponent(
                                                                                                                                                                                                                                                                                                                                                                                                                  "Log in or sign up to send a gift."
                                                                                                                                                                                                                                                                                                                                                                                                                        )}&next=${encodeURIComponent(`/artists/${artistId}`)}`
                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                const { data: artist, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                    .from("artists")
                                                                                                                                                                                                                                                                                                                                                                                                                                        .select("id, is_active, profiles ( display_name )")
                                                                                                                                                                                                                                                                                                                                                                                                                                            .eq("id", artistId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                .single();
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (error || !artist) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      throw new Error("Could not find that artist.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                          if ((artist as any).is_active === false) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              throw new Error("This artist isn't available to receive gifts right now.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const artistName = (artist as any).profiles?.display_name ?? "this artist";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const amountCents = Math.round(amountDollars * 100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const session = await stripe.checkout.sessions.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mode: "payment",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                billing_address_collection: "required",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line_items: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  price_data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currency: "usd",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      unit_amount: amountCents,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                product_data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: `Gift to ${artistName}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...(message ? { description: message.slice(0, 500) } : {}),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  quantity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success_url: `${siteUrl}/artists/${artistId}?gift=success`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cancel_url: `${siteUrl}/artists/${artistId}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        metadata: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type: "gift",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    artist_id: artistId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fan_id: user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                amount_cents: String(amountCents),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...(message ? { gift_message: message.slice(0, 500) } : {}),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!session.url) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throw new Error("Stripe did not return a checkout URL.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      redirect(session.url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
